-- 코드를 입력하세요
SELECT CRCRH.CAR_ID, IF(MT.CAR_ID IS NULL, '대여 가능', '대여중') AS AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY CRCRH LEFT JOIN (
    SELECT *
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE <= '2022-10-16' AND END_DATE >= '2022-10-16'
    GROUP BY CAR_ID
) MT
ON CRCRH.CAR_ID = MT.CAR_ID
GROUP BY CRCRH.CAR_ID
ORDER BY CRCRH.CAR_ID DESC;
