-- 코드를 작성해주세요
WITH FE AS
(
    SELECT SUM(CODE) AS FE_SKILL
    FROM SKILLCODES
    GROUP BY CATEGORY
    HAVING CATEGORY LIKE 'Front End'
)

SELECT ID, EMAIL, FIRST_NAME, LAST_NAME
FROM DEVELOPERS D, FE
WHERE D.SKILL_CODE & FE.FE_SKILL > 1
ORDER BY ID;


