-- 코드를 입력하세요
WITH MEMBER_REVIEW AS 
(
    SELECT MP.MEMBER_ID, MEMBER_NAME
    FROM MEMBER_PROFILE MP JOIN REST_REVIEW RR
    ON MP.MEMBER_ID = RR.MEMBER_ID
    GROUP BY MP.MEMBER_ID
    ORDER BY COUNT(REVIEW_ID) DESC
    LIMIT 1
)

SELECT MEMBER_NAME, REVIEW_TEXT, DATE_FORMAT(REVIEW_DATE, '%Y-%m-%d') REVIEW_DATE
FROM MEMBER_REVIEW MR LEFT JOIN REST_REVIEW RR
ON MR.MEMBER_ID = RR.MEMBER_ID
ORDER BY REVIEW_DATE, REVIEW_TEXT;
